name: Build, publish, and deploy elesson to SmarterASP.NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Migrate
        run: dotnet ef database update --connection ${{secrets.ELEARNING_CONNECTION_STRING}}

      - name: Publish
        run: dotnet publish --configuration Release -o publish --no-build 

      - name: Deploy to SmarterASP.NET
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: lankiman-001-site1  # Replace with your SmarterASP.NET site name
          server-computer-name: https://win6145.site4now.net:8172
          server-username: lankiman-001
          server-password: ${{ secrets.ELESSON_PASSWORD }}  # Replace with your secret for SmarterASP.NET password
          target-delete: true


      
          
